name: "Tidbyt Server"
description: "Pixlet server for Tidbyt"
version: "1.0.0"
slug: "ha_tidbyt"
init: false
arch:
  - aarch64
  - amd64
startup: services
ports:
  8000/tcp: 8000
webui: http://[HOST]:[PORT:8000]
homeassistant_api: true
options:
  pixlet_data: |
    load("render.star", "render")
    def main():
      return render.Root(
        child = render.Text("Hello, World!")
    )
  entity_id: "home"
schema:
  pixlet_data: str
  entity_id: str
